search:
  name: Search
  description: Emulates opening the search screen and entering the search keyword.
  target:
    entity:
      integration: mediatracker
      domain: calendar
  fields:
    keyword:
      name: Keyword
      description: The keyword to search for.
      required: true
      example: "Enshrouded"
      selector:
        text:
